import Config

# Development only. The live site is a MIX_ENV=prod release: its settings are
# config/prod.exs (fixed at build time) and config/runtime.exs (read from the
# environment at boot), and nothing in this file reaches it.
#
# Until September 2026 the site was served by `mix phx.server` in this
# environment, with a PUBLIC_DEPLOY switch in this file that turned it into a
# production config. That switch is gone with the deploy it served; what
# survives of it is the habit it taught, which is that nothing below is a
# secret. Every value here is published in a public repository.

# Not secrets: these sign nothing but a development session on localhost.
config :web, :session_signing_salt, "dev_only_salt"
config :web, :secure_cookies?, false

# Configure your database
#
# Both debug flags are the right defaults for a local console and the wrong
# ones for a machine serving traffic: `stacktrace` attaches one to every
# query, and `show_sensitive_data_on_connection_error` puts connection
# parameters into the log when the database refuses a connection.
config :web, Web.Repo,
  database: Path.expand("../web_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :web, WebWeb.Endpoint,
  # PORT lets a development server run beside the live site, which holds 4000
  # on this machine.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  url: [host: "localhost", port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  # Both of these leak, which is why production has neither: debug_errors
  # renders stacktraces, request params and session contents to whoever
  # tripped the crash, and code_reloader exposes a live-reload socket and takes
  # a compile lock on every request.
  code_reloader: true,
  debug_errors: true,
  secret_key_base: String.duplicate("dev_only_insecure_secret_key_base", 2),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:web, ~w(--watch)]}
  ],
  live_view: [signing_salt: "dev_only_lv_salt"]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :web, WebWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/web_web/router\.ex$"E,
      ~r"lib/web_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# LiveDashboard and the Swoosh mailbox preview, under /dev. Development only:
# they were once reachable on the public site (process inspector, ETS browser,
# ecto_stats, all unauthenticated), so router.ex also gates the scope on an
# admin session at runtime, and ./redeploy.sh fails a deploy that answers them.
config :web, dev_routes: true

# The admin password for a development server. Production takes
# ADMIN_PASSWORD from the environment and will not boot without it.
config :web, :admin_password, "dev-admin"

# Komoot auto-sync credentials (optional — sync is disabled when unset).
config :web, :komoot,
  email: System.get_env("KOMOOT_EMAIL"),
  password: System.get_env("KOMOOT_PASSWORD")

# The places no activity may be shown near (`lat,lng`; see config/runtime.exs).
config :web, :ride_privacy_zones, System.get_env("RIDE_PRIVACY_ZONES")
config :web, :health_webhook_token, System.get_env("HEALTH_WEBHOOK_TOKEN")

# Second copy of each snapshot, on a different physical disk. Snapshots that
# live beside the database only protect against a bad deploy or a mistaken
# DELETE — one failed volume takes the database and every snapshot together.
# Unset is fine and is the normal case on a checkout that is not the server;
# an unplugged drive is skipped with a log line, never an error.
config :web, :backup_mirror_path, System.get_env("BACKUP_MIRROR_PATH")

# The negatives archive. Web.Backup only ever snapshots the database, which left
# 317 MB of scanned film — the one thing here that cannot be re-derived from
# Komoot, git or anywhere else — with no backup at all.
config :web, :photos_mirror_path, System.get_env("PHOTOS_MIRROR_PATH")

# The written content's versions and the captain's logs' media, likewise.
config :web, :content_mirror_path, System.get_env("CONTENT_MIRROR_PATH")
config :web, :uploads_mirror_path, System.get_env("UPLOADS_MIRROR_PATH")

# A development server keeps its own backups, and keeps to itself.
#
# Web.Backup's default folder is the live site's, under $HOME. That is right
# for the deploy and wrong for `mix phx.server` on the same machine: a snapshot
# of web_dev.db written there would sit among the live snapshots as the newest
# of them, which is the one a restore reaches for, and would push a real one
# out of the fourteen that are kept. BACKUP_PATH and CONTENT_BACKUP_PATH still
# win.
#
# Nor does it announce anything to other sites. The posts it reads are the
# real ones, and it would send their citations out again from localhost.
config :web,
       :backup_path,
       System.get_env("BACKUP_PATH") || Path.expand("../tmp/dev_backups/db", __DIR__)

config :web,
       :content_backup_path,
       System.get_env("CONTENT_BACKUP_PATH") ||
         Path.expand("../tmp/dev_backups/content", __DIR__)

config :web, :webmention_send, false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Every query and every LiveView diff: right for a console, and the reason
# config/prod.exs sets :info.
config :logger, level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # These stamp every element with its template file and line number
  # (data-phx-loc="27"). Changing them needs `mix clean` and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Helpful, and documented as expensive: not for serving traffic.
  enable_expensive_runtime_checks: true

# Enable swoosh api client for Resend adapter
config :swoosh, :api_client, Swoosh.ApiClient.Finch

# Use Resend for reliable email delivery
# Get your free API key at https://resend.com
config :web, Web.Mailer,
  adapter: Swoosh.Adapters.Resend,
  api_key: System.get_env("RESEND_API_KEY")

# The scanner studio invents its scans when no scanner is attached. Never set
# in production: an invented strip there lands in the real archive.
config :web, :scanner_simulation, true

config :web, :scanner_areas, %{
  "35mm" => System.get_env("SCANNER_AREA_35MM"),
  "120" => System.get_env("SCANNER_AREA_120")
}
