import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :web, WebWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# `force_ssl` is deliberately not set. Caddy is the only thing that listens on
# 80 and 443: it redirects plain HTTP and sends the HSTS header itself. The
# release listens on :4000 for Caddy and for the deploy script's health checks
# on localhost, which a redirect to https would break.

# The session cookie carries the admin's login, so it is only ever sent over
# TLS. Read when the endpoint compiles (it is a module attribute there), so it
# is set here and not in runtime.exs. This was lost when the site moved from
# the old dev-mode deploy to a release: the flag lived in config/dev.exs.
config :web, :secure_cookies?, true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
